# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Assayward < Formula
  desc "Evaluate supply-chain evidence against a declarative policy"
  homepage "https://github.com/sns45/assayward"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sns45/assayward/releases/download/v0.1.0/assayward_darwin_amd64.tar.gz"
      sha256 "68cfc5e354a7be434e16f24c6f3f92d559398d11b80245eda1134d77b6dafdef"

      define_method(:install) do
        bin.install "assayward"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sns45/assayward/releases/download/v0.1.0/assayward_darwin_arm64.tar.gz"
      sha256 "d25564ba59cadbd29219c7070e87ec396139826eb5950e0714cb77de5eb33261"

      define_method(:install) do
        bin.install "assayward"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sns45/assayward/releases/download/v0.1.0/assayward_linux_amd64.tar.gz"
      sha256 "5493250a4d1b2eab28ddc93e01aa51cb83e4846fcfbfad4328f2443ea03dd65f"
      define_method(:install) do
        bin.install "assayward"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sns45/assayward/releases/download/v0.1.0/assayward_linux_arm64.tar.gz"
      sha256 "7ca04b1ca3fd51e5c83dad68aae92467c4cfdb10842a455a75557eb135cc3984"
      define_method(:install) do
        bin.install "assayward"
      end
    end
  end

  test do
    system "#{bin}/assayward", "--version"
  end
end
