# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Assayward < Formula
  desc "Evaluate supply-chain evidence against a declarative policy"
  homepage "https://github.com/sns45/assayward"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sns45/assayward/releases/download/v0.2.0/assayward_darwin_amd64.tar.gz"
      sha256 "6b45b15444e112a5929130a7649fff19e675243728be086c97af55284b90360c"

      define_method(:install) do
        bin.install "assayward"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sns45/assayward/releases/download/v0.2.0/assayward_darwin_arm64.tar.gz"
      sha256 "8cd070927c6c62f778046e1c33198709d9eaa22907b245bc989191a32166eebe"

      define_method(:install) do
        bin.install "assayward"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sns45/assayward/releases/download/v0.2.0/assayward_linux_amd64.tar.gz"
      sha256 "9b2d991a09c3dcb3c78fa460b067b43093bb67e3c991ba07b217135389d1bce9"
      define_method(:install) do
        bin.install "assayward"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sns45/assayward/releases/download/v0.2.0/assayward_linux_arm64.tar.gz"
      sha256 "c33bbb8e15d0a0d2a597bf1d9c07d63bb36ef1445726040f8f5d7d3c6e940aff"
      define_method(:install) do
        bin.install "assayward"
      end
    end
  end

  test do
    system "#{bin}/assayward", "--version"
  end
end
