# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Svidmint < Formula
  desc "SPIFFE compatible workload identity for serverless and edge environments"
  homepage "https://github.com/sns45/svidmint"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sns45/svidmint/releases/download/v0.1.0/svidmint_0.1.0_darwin_amd64.tar.gz"
      sha256 "e8b1769b1b047cfb5505783dc88137baa22b40ac626a3475c50a2d1420133b18"

      define_method(:install) do
        bin.install "svidmint"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sns45/svidmint/releases/download/v0.1.0/svidmint_0.1.0_darwin_arm64.tar.gz"
      sha256 "abbd02b7fbc58b8de41f2bf6ec791b59da7db9aad21356a05fdb2b2c8b629db0"

      define_method(:install) do
        bin.install "svidmint"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sns45/svidmint/releases/download/v0.1.0/svidmint_0.1.0_linux_amd64.tar.gz"
      sha256 "1fbd3e947f626af69d366ff522bc73241f59db6082eebfcdaa640521790bb094"
      define_method(:install) do
        bin.install "svidmint"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sns45/svidmint/releases/download/v0.1.0/svidmint_0.1.0_linux_arm64.tar.gz"
      sha256 "d965626fd7db3006c53ce573b17c08679119987fc1f12bf9ee75f966f273dddb"
      define_method(:install) do
        bin.install "svidmint"
      end
    end
  end

  test do
    system "#{bin}/svidmint", "version"
  end
end
