# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tickettok < Formula
  desc "Terminal Kanban dashboard for managing multiple Claude Code agents via tmux"
  homepage "https://github.com/sns45/tickettok"
  version "0.1.0"
  license "MIT"

  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sns45/tickettok/releases/download/v0.1.0/tickettok_darwin_amd64.tar.gz"
      sha256 "17f74c9fc39924c2df5a14a82325862a6c785a036f8ebc25ac164f699816ec81"

      def install
        bin.install "tickettok"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sns45/tickettok/releases/download/v0.1.0/tickettok_darwin_arm64.tar.gz"
      sha256 "9738984eec198a6374b6a473fdc0ffd523c1d0707915e3ce45fc19face727496"

      def install
        bin.install "tickettok"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sns45/tickettok/releases/download/v0.1.0/tickettok_linux_amd64.tar.gz"
      sha256 "6b28bb64a6f02260a529dad8ebc6858f7f3cd01be5dd33c34faf204435891b77"
      def install
        bin.install "tickettok"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sns45/tickettok/releases/download/v0.1.0/tickettok_linux_arm64.tar.gz"
      sha256 "38b11b09257a399919f9cc9bf7bdf0f5eab2d3d9e5e5580ed4abf2e4b9c21ada"
      def install
        bin.install "tickettok"
      end
    end
  end

  test do
    assert_match "tickettok", shell_output("#{bin}/tickettok version")
  end
end
