# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tickettok < Formula
  desc "Terminal Kanban dashboard for managing multiple Claude Code agents via tmux"
  homepage "https://github.com/sns45/tickettok-releases"
  version "0.19.0"
  license "Proprietary"

  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sns45/tickettok-releases/releases/download/v0.19.0/tickettok_darwin_amd64.tar.gz"
      sha256 "7de7fcc38c349ae08ea378a96ab5facfe5ba3e46d221ad85ce628770de3aa684"

      define_method(:install) do
        bin.install "tickettok"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sns45/tickettok-releases/releases/download/v0.19.0/tickettok_darwin_arm64.tar.gz"
      sha256 "d3c06e327423fe99014c8e521486c98ece3ac321a5e96f5900f60d7ff9bbcd8a"

      define_method(:install) do
        bin.install "tickettok"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sns45/tickettok-releases/releases/download/v0.19.0/tickettok_linux_amd64.tar.gz"
      sha256 "5f52620b70af9b6e882cc77351d2c1e18fc4f8bfa300103f73feda4cb336459f"
      define_method(:install) do
        bin.install "tickettok"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sns45/tickettok-releases/releases/download/v0.19.0/tickettok_linux_arm64.tar.gz"
      sha256 "aa1d3c8806b5e6600ea9161ba1f401dc7693e4b6f0815e272410f6be899a22b1"
      define_method(:install) do
        bin.install "tickettok"
      end
    end
  end

  test do
    assert_match "tickettok", shell_output("#{bin}/tickettok version")
  end
end
