# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tickettok < Formula
  desc "Terminal Kanban dashboard for managing multiple Claude Code agents via tmux"
  homepage "https://github.com/sns45/tickettok-releases"
  version "0.7.1"
  license "Proprietary"

  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sns45/tickettok-releases/releases/download/v0.7.1/tickettok_darwin_amd64.tar.gz"
      sha256 "1e299e148d26fc880375ec0c456cfed118119620bea89473ecd36ccbe1f1c551"

      define_method(:install) do
        bin.install "tickettok"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sns45/tickettok-releases/releases/download/v0.7.1/tickettok_darwin_arm64.tar.gz"
      sha256 "d66cad4c6e3df3b96abdf71c63464f3a4290070b006042975beebd91e66ce4ff"

      define_method(:install) do
        bin.install "tickettok"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sns45/tickettok-releases/releases/download/v0.7.1/tickettok_linux_amd64.tar.gz"
      sha256 "ba0f3303e5a1d04ae964780bcdd79e8be2408d2bd9dd0424d49790425d3c089b"
      define_method(:install) do
        bin.install "tickettok"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sns45/tickettok-releases/releases/download/v0.7.1/tickettok_linux_arm64.tar.gz"
      sha256 "4a42ef7e8b297eaf6163850d04f0a47ddd373ea52b731c7c8d52b6114885d3a3"
      define_method(:install) do
        bin.install "tickettok"
      end
    end
  end

  test do
    assert_match "tickettok", shell_output("#{bin}/tickettok version")
  end
end
