# This file was generated by GoReleaser. DO NOT EDIT.
cask "smithmark" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "7f828949932d97b0185d7811228518d51269e76ba8bb87eb745685e5c2244ef9"
      url "https://github.com/sns45/smithmark/releases/download/v#{version}/smithmark_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "fff95057aaab21a9b3c878d444c7bcd5c4de118b810e5e0035ef1186e8c9e4e4"
      url "https://github.com/sns45/smithmark/releases/download/v#{version}/smithmark_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2a8e3d93e60dc88beaba6a07b5d8bdb0dbe9f4e27b678f71571a9b12952669f2"
      url "https://github.com/sns45/smithmark/releases/download/v#{version}/smithmark_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3f5c6e1b168cfd0dc406dd213efe848741d05eecce8dae3b6211e1581515447c"
      url "https://github.com/sns45/smithmark/releases/download/v#{version}/smithmark_#{version}_linux_arm64.tar.gz"
    end
  end

  name "smithmark"
  desc "Provenance and capability attestation for the agent tool supply chain (MCP servers and skills)"
  homepage "https://github.com/sns45/smithmark"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "smithmark"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/smithmark"]
    end
  end

  # No zap stanza required

end
