# This file was generated by GoReleaser. DO NOT EDIT.
cask "smithmark" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "0e3b19c1a21bf894099709257faa05c20d4bd9f317ed78db93c40b93acac56be"
      url "https://github.com/sns45/smithmark/releases/download/v#{version}/smithmark_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "72a60d9a5d255f6a7ac3d57e93f494743595edf4294e47580f7a48da58c2880c"
      url "https://github.com/sns45/smithmark/releases/download/v#{version}/smithmark_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "95e0f3d2d6b4e4cee70ddfde8718c5f5d7261754c2d2cee766476ffe7126783d"
      url "https://github.com/sns45/smithmark/releases/download/v#{version}/smithmark_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1d461194e50c63776ce386b47208f6ace1f7c90520f1bb0981f104357196d322"
      url "https://github.com/sns45/smithmark/releases/download/v#{version}/smithmark_#{version}_linux_arm64.tar.gz"
    end
  end

  name "smithmark"
  desc "Provenance and capability attestation for the agent tool supply chain (MCP servers and skills)"
  homepage "https://github.com/sns45/smithmark"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "smithmark"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/smithmark"]
    end
  end

  # No zap stanza required

end
