# This file was generated by GoReleaser. DO NOT EDIT.
cask "smithmark" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "d28fc7b534f110267b557cd284177bad67522e2b6497f65d7f01a8e0521db09e"
      url "https://github.com/sns45/smithmark/releases/download/v#{version}/smithmark_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "62d41a69b7980a4b7bc15e448647c828ad1716d33ededfaaab02962a91763faf"
      url "https://github.com/sns45/smithmark/releases/download/v#{version}/smithmark_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f74c6c22b4dba3b16da166bde88593cac7938e61ccdd7feddd5a7348e642a399"
      url "https://github.com/sns45/smithmark/releases/download/v#{version}/smithmark_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f17e749721aa5f00df93236d12b8449fbc58af1583c8dbbf3ceb40d51950816c"
      url "https://github.com/sns45/smithmark/releases/download/v#{version}/smithmark_#{version}_linux_arm64.tar.gz"
    end
  end

  name "smithmark"
  desc "Provenance and capability attestation for the agent tool supply chain (MCP servers and skills)"
  homepage "https://github.com/sns45/smithmark"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "smithmark"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/smithmark"]
    end
  end

  # No zap stanza required

end
